default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  port: 5432
  host: localhost

development:
  <<: *default
  database: appStreetDemoApp

test:
  <<: *default
  database: appStreetDemoApp
